name: vascx-fork
channels:
  - defaults
dependencies:
  - click=8
  - numpy=2
  - pandas=2
  - pillow=11
  - pip
  - pydantic=2
  - python=3.11
  - pyyaml=6
  - tqdm=4
  - pytest
  - scikit-image
  - pip:
      - huggingface_hub
      - torch==2.11.0
      - torchvision==0.26.0
      - torchaudio==2.11.0
      - PyMuPDF
      - retinalysis-fundusprep
      - retinalysis-inference
